### ISSUE TITLE
lambda model serving / optimize 이미지 생성

### ISSUE THREAD

**Issue by subeans** [ddps-lab/lambda-optimize-serving#1]
lambda 이미지 생성 
1. s3 에 있는 모델을 가져와 serving 하는 이미지( torch serving , onnx serving , tvm serving ) 
2. torch 원본 모델을 optimize 해서 s3에 저장하는 lambda이미지 ( onnx - graph optimize , tvm - hardware optimize )

**Comment by jaeriver** [comment]
현재 s3 upload가 tvm의 경우 안되는 문제가 있어 디버깅 후 수정 예정

**Comment by kmu-leeky** [comment]
tvm 모델의 경우 s3 업로드가 안된다는게 뭔가 선뜻 이해가 가지는 않는 상황인것 같은데. s3-tvm 만의 특징적인 이슈가 있는건가?

**Comment by jaeriver** [comment]
제가 아직 디버깅을 제대로 해보진 못했으나 s3 에 업로드 하는 작업이 현재 tvm에서는 제대로 동작하지 않는 상황입니다. 단순한 코드 작업 문제일 수 있고 혹은 파일 차이에 의한 문제일 수 있습니다. 디버깅을 진행해보겠습니다.
