### ISSUE TITLE
Torch, Onnx, TVM Serving 코드 전반적 수정

### ISSUE THREAD

**Issue by jaeriver** [ddps-lab/lambda-optimize-serving#2]
사용자의 웹에 response를 줄 때, 추론 성능과 더불어 해당 모델의 정확도 또한 표현해 주어야 할 것 같습니다.
따라서 정확도를 return 하는 코드를 추가합니다.
정확도에 대해서 표현을 해주어야 할지 우선 논의가 필요합니다.

**Comment by subeans** [comment]
저는 사용자의 실제 데이터를 입력으로 받지 않고, 데이터 shape만 받기 때문에 정확도가 필요없을 것 같다는 생각입니다. 
이에 따른 논의가 필요합니다

**Comment by jaeriver** [comment]
현재 람다 serving 코드를 짜면서 고민되는 요소들 입니다.

- load_model을 매번 진행하도록 하는데 global 하게 한번만 load 하도록 수정해야할지 고민입니다.
- model inference의 정확도도 return 해주어야 할지 고민입니다.
- 사용자의 image data 등 input을 받아 처리할지 input shape같은 정보를 받을지 아예 받지 않고 처리할지 고민입니다.
- inference 작업을 내부적으로 여러번 돌려 min, max, avg 값등을 return 할지 1번만 돌릴 지 고민입니다.
만약 여러번 돌린다면, 몇번 돌릴지를 사용자에게 파라미터 값으로 받아야 할지 고려 중입니다.

**Comment by jaeriver** [comment]
전반적인 작업은 마무리 된 듯 하나, 추후 EFS 사용 혹은 Step Function 연결에서 parameter를 받는 코드가 변경될 수 있음

**Comment by kmu-leeky** [comment]
파라미터 등을 통해서 시스템이 다양한 시나리오를 지원하는 능력을 키워주는것도 좋을것 같아. 그정도 복잡해지는건 충분히 수용 가능할것 같으니.
