### ISSUE TITLE
추가 개발 사항 정리

### ISSUE THREAD

**Issue by jaeriver** [ddps-lab/lambda-optimize-serving#28]
- model size 파라미터 bytes 단위로 받기
- 클라이언트에서 model input size도 받기
- 클라이언트에서 workload 종류 정하기 (이미지 분류, 자연어 처리 등)
- 자연어 처리 inference 작업 진행

**Comment by kmu-leeky** [comment]
오케이. 재강아 이걸 별개의 이슈로 생성해서 관리하는게 좋을것 같아. 우선은 to-do 리스트로 별개의 이슈들로 만들어두자.

**Comment by kmu-leeky** [comment]
재강아 보통 이런 이슈들은 작업하지 않더라도 만들어서 to-do 넣어두고 언제든지 작업을 할때 in-progress 로 옮기는게 일반적이야. to-do 에 있다가 작업하지 않으면 그냥 done 으로 옮겨버려도 되니까. 오히려 따로 기록해두지 않으면 나중에 잊어버리게 되더라고. 이슈 만드는건 편하게 계속 만들어도 괜찮아.
