### ISSUE TITLE
[AYCI] json파일을 pandas dataframe으로 변환하기

### ISSUE THREAD

**Issue by HeeNamgoong** [ddps-lab/lambda-optimize-serving#57]
s3에 저장되어 있는 json 파일들이 너무 많아 하나하나 값을 따로 보기 어려워 pandas를 이용해 한 눈에 보기 쉽도록 python구현을 하였습니다. 재강님과 수빈님께서 할당해주셨습니다.

**Comment by HeeNamgoong** [comment]
수행한 작업을 정리하였습니다.
https://dog-universe-67a.notion.site/Convert-Json-into-Pandas-Dataframe-6ddf013a5b79410fbbce1b273a973e17

**Comment by kmu-leeky** [comment]
이 작업을 하는 목적은 무엇인가요?

**Comment by HeeNamgoong** [comment]
현재 s3의 json파일이 넘쳐나 데이터를 읽어오는 과정에서 한눈에 보기 어려워 pandas dataframe을 통해 여러 개의 json파일을 한 행에 보여주며 data를 한눈에 보기 쉽게 나타내기 위함입니다!

**Comment by kmu-leeky** [comment]
어떤 json 파일이에요? 핵심 기능 구현에 필요한 json 파일인지, 아니면 일종의 상태 모니터링을 위한 메타데이터 용의 json 파일인건가요?

**Comment by HeeNamgoong** [comment]
후자입니다! 수빈님, 재강님이 lambda stepfunction 진행하고 난 실험 결과 json파일로 알고있습니다.

**Comment by subeans** [comment]
해당 이슈는 더 진행사항이 없으므로 close 합니다.
