### ISSUE TITLE
[Action Required] Please update to the latest Neuron Driver (aws-neuron-dkms version 2.3.26 or newer) 

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/lambda-optimize-serving#64]
업데이트 관련한 이메일 옴

[Root: BigData Lab in KMU]

Hello,

Our records indicate that during the last 12 months you have used the EC2 Inf1 instances [1] with this account.  AWS Neuron [2] is the SDK for Inf1 instances and is integrated in machine learning (ML) frameworks like PyTorch and TensorFlow.  We are asking that you update the Neuron Driver to the latest (version 2.3.26 or newer) so that you can benefit from operational and security updates.

*What do I need to do?*
You must update to the latest Neuron Driver (aws-neuron-dkms version 2.3.26 or newer) before installing or upgrading to latest Neuron release.

#If you are using Ubuntu please run:

1) Configure Linux for Neuron repository updates
. /etc/os-release
sudo tee /etc/apt/sources.list.d/neuron.list > /dev/null <<EOF
deb https://apt.repos.neuron.amazonaws.com/ ${VERSION_CODENAME} main
EOF
wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -

2) Update OS packages
sudo apt-get update -y

3) Install OS headers
sudo apt-get install linux-headers-$(uname -r) -y

4) Install Neuron Driver
sudo apt-get install aws-neuron-dkms -y
​
#If you are using Amazon Linux 2 please run:

1) Configure Linux for Neuron repository updates
sudo tee /etc/yum.repos.d/neuron.repo > /dev/null <<EOF
[neuron]
name=Neuron YUM Repository
baseurl=https://yum.repos.neuron.amazonaws.com/
enabled=1
metadata_expire=0
EOF
sudo rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

2) Update OS packages
sudo yum update -y

3) Install OS headers
sudo yum install kernel-devel-$(uname -r) kernel-headers-$(uname -r) -y

4) Remove existing Neuron Driver
sudo yum remove aws-neuron-dkms

5) Install Neuron Driver
sudo yum install aws-neuron-dkms -y
​
For full installation instructions please check the Neuron setup guide [4] on Neuron documentation.
​
If you have any questions or concerns about this change or if you are facing issues please send an email to “[neuron-support@amazon.com](mailto:neuron-support@amazon.com)”, open a Github issue [5] or post a question in Neuron AWS forums [6].
​
[1] https://aws.amazon.com/ec2/instance-types/inf1/
[2] https://aws.amazon.com/machine-learning/neuron/
[3] https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html
[4] https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/neuron-install-guide.html
[5] https://github.com/aws/aws-neuron-sdk/issues
[6] https://forums.aws.amazon.com/forum.jspa?forumID=355

Sincerely,
Amazon Web Services

**Comment by jaeriver** [comment]
네 교수님 이메일 내용을 기존 공식 문서에서 확인했었어서 Inferentia 세팅을 할 때 이미 해당 업데이트를 진행 완료했었습니다

**Comment by kmu-leeky** [comment]
nice!
