### ISSUE TITLE
[AYCI] 에러 처리

### ISSUE THREAD

**Issue by workdd** [ddps-lab/lambda-optimize-serving#67]
현재 에러 발생을 하면 어떠한 response없이 step function이 중단됩니다.

따라서 에러 상황을 파악하고 코드상으로 처리하여 해당 에러에 대한 response를 보내주는 처리가 필요합니다.

**Comment by subeans** [comment]
현재까지 파악되는 대표적인 에러는 아래 세 가지와 같습니다. 
1. 메모리, 스토리지 부족에러 발생 
2. convert 후 모델 파일이 s3에 저장되는데 지연이 생겨 serving 람다 진행시 model load 시 에러 발생 
3. archive lambda 에서 cloudwatch log 가져오는데 지연이 생겨 에러 발생

**Comment by subeans** [comment]
현재 메모리, 스토리지 부족 에러같은 경우 예측 모델을 생성하여 OOM classification 한다면 에러 발생률을 줄일 수 있을 것이라고 판단되며 
archive lambda의 used memory가져오는 과정에서의 에러는 150초로 wait시간을 늘려 에러 발생률을 줄였습니다. 

마지막 이슈에 대해서 자세히 설명을 하자면, 
convert 는 람다 메모리 별로 일어나지 않는 부분입니다. 현재 코드상으로는 고정된 메모리로 convert가 진행되며 다양한 람다 메모리별 serving 요청이 들어왔을 때 같은 작업(convert)을 각각의 메모리 stepfunction에서 중복으로 진행되게 됩니다. 
serving 시 s3에 업로드한 model 에 접근하게 되는데 만약 다른 stepfunction에서 convert 후 모델을 덮어쓰기 중이라면 serving시 tar 파일관련 error가 발생하게 됩니다. 
때문에 특별한 코드 수정 없이, 다른 stepfunction 이 convert 후 model upload하는 타이밍만 겹치지 않는다면 에러가 발생하지 않습니다. 
이에 대해 해결책으로 convert 부분을 stepfunction에서 제외를 할지에 대한 논의도 필요할 것 같습니다.

**Comment by subeans** [comment]
convert lambda 이미지 복원 불가능 에러 


![Image](https://user-images.githubusercontent.com/39542978/183349609-83adc078-3557-48c6-8c69-610d5d9e734b.png)

이전에 재강이와 줌 미팅을 할 당시 함수 복원에러가 발생했었습니다. 그때 당시 ECR에 이미지가 없는 경우로 확인하고 이미지를 추가하면서 해결이 되었지만 이번 경우에는 ECR에 이미지가 있는 경우에도 에러가 발생합니다. 
새 이미지 배포로 ECR에 있는 이미지를 재 할당을 해주는 경우 에러해결이 되기는 하지만 지속적으로 복원이 안되는 문제에 대해서 자동화코드를 살펴보거나 다른 이유가 있을지 확인해보아야할 것 같습니다.

**Comment by subeans** [comment]
에러 처리와 관련해서 각각 이슈를 따로 만들어 해결해야할 것 같아 해당 이슈를 닫겠습니다.
