### ISSUE TITLE
[ AYCI ] archive lambda 의 cloudwatch log 지연으로 인한 에러

### ISSUE THREAD

**Issue by subeans** [ddps-lab/lambda-optimize-serving#68]
추론을 진행하고 저장하는 단계에서 Max memory used 를 cloud watch log를 보고 지표를 가져옵니다. 
이때 cloud watch log 지연으로 인해 response를 제대로 못가져오는 경우가 발생하여 wait 을 2분을 설정하였지만
2분도 부족한 경우가 발생하여 150초 혹은 180초(3분)으로 늘려서 진행합니다. 

wait 시간을 늘림에 따라 발생할 수 있는 이슈를 생각하고 ses 전송하는 방법에 대해서도 다시 고려해볼 필요가 있습니다.

**Comment by workdd** [comment]
추후 코드상에서 try except 처리를 해야할 수 있습니다. 혹은 result를 분리하는 방안을 고려해볼 수 있습니다. 우선 step function 단에서 처리 후 진행 여부를 고려해보겠습니다

**Comment by subeans** [comment]
stepfunction의 설정만으로 해결하여 101번 이슈가 close 됨에 따라 함께 close합니다.
